In [1]:
import pandas as pd
import numpy as np

In [2]:
df_compras = pd.read_csv('shopping_behavior_updated.csv')

In [3]:
# Dropar a coluna de identificador Ãºnico
df_compras = df_compras.drop(columns=['Customer ID'])
df_compras

,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [4]:
#Tratar o nome das colunas
df_compras.columns = df_compras.columns.str.lower()
df_compras.columns = df_compras.columns.str.replace(' ', '_')
df_compras.columns = df_compras.columns.str.replace('(', '')
df_compras.columns = df_compras.columns.str.replace(')', '')
df_compras

C:\Users\paula\AppData\Local\Temp\ipykernel_14792\1939859129.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_compras.columns = df_compras.columns.str.replace('(', '')
C:\Users\paula\AppData\Local\Temp\ipykernel_14792\1939859129.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_compras.columns = df_compras.columns.str.replace(')', '')

,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

Tratamento dos dados categÃ³ricos

In [5]:
#Trocar colunas subscription_status, discount_applied e promo_code_used por binÃ¡rio
df_compras = pd.get_dummies(df_compras, columns=['subscription_status', 'discount_applied', 'promo_code_used'], drop_first=True)
df_compras

,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,shipping_type,previous_purchases,payment_method,frequency_of_purchases,subscription_status_Yes,discount_applied_Yes,promo_code_used_Yes
0,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Express,14,Venmo,Fortnightly,1,1,1
1,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Express,2,Cash,Fortnightly,1,1,1
2,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Free Shipping,23,Credit Card,Weekly,1,1,1
3,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Next Day Air,49,PayPal,Weekly,1,1,1
4,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Free Shipping,31,PayPal,Annually,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,2-Day Shipping,32,Venmo,Weekly,0,0,0
3896,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,Store Pickup,41,Bank Transfer,Bi-Weekly,0,0,0
3897,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,Standard,24,Venmo,Quarterly,0,0,0
3898,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,Express,24,Venmo,Weekly,0,0,0
3899,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,Store Pickup,33,Venmo,Quarterly,0,0,0

In [7]:
# Drop coluna Promo Code Used
df_compras = df_compras.drop(columns=['promo_code_used_Yes'])
df_compras

,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,shipping_type,previous_purchases,payment_method,frequency_of_purchases,subscription_status_Yes,discount_applied_Yes
0,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Express,14,Venmo,Fortnightly,1,1
1,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Express,2,Cash,Fortnightly,1,1
2,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Free Shipping,23,Credit Card,Weekly,1,1
3,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Next Day Air,49,PayPal,Weekly,1,1
4,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Free Shipping,31,PayPal,Annually,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,2-Day Shipping,32,Venmo,Weekly,0,0
3896,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,Store Pickup,41,Bank Transfer,Bi-Weekly,0,0
3897,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,Standard,24,Venmo,Quarterly,0,0
3898,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,Express,24,Venmo,Weekly,0,0
3899,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,Store Pickup,33,Venmo,Quarterly,0,0

In [8]:
# Transformando Gender em binÃ¡rio
gender_get_dummies = df_compras['gender'].str.get_dummies()
gender_get_dummies

      Female  Male
0          0     1
1          0     1
2          0     1
3          0     1
4          0     1
...      ...   ...
3895       1     0
3896       1     0
3897       1     0
3898       1     0
3899       1     0

[3900 rows x 2 columns]

In [9]:
# Mantendo apenas uma das colunas
df_compras = pd.concat([df_compras, gender_get_dummies], axis=1)
df_compras = df_compras.drop(columns=['gender','Male'])
df_compras

,age,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,shipping_type,previous_purchases,payment_method,frequency_of_purchases,subscription_status_Yes,discount_applied_Yes,Female
0,55,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Express,14,Venmo,Fortnightly,1,1,0
1,19,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Express,2,Cash,Fortnightly,1,1,0
2,50,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Free Shipping,23,Credit Card,Weekly,1,1,0
3,21,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Next Day Air,49,PayPal,Weekly,1,1,0
4,45,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Free Shipping,31,PayPal,Annually,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,40,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,2-Day Shipping,32,Venmo,Weekly,0,0,1
3896,52,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,Store Pickup,41,Bank Transfer,Bi-Weekly,0,0,1
3897,46,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,Standard,24,Venmo,Quarterly,0,0,1
3898,44,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,Express,24,Venmo,Weekly,0,0,1
3899,52,Handbag,Accessories,81,California,M,Beige,Spring,3.1,Store Pickup,33,Venmo,Quarterly,0,0,1

In [10]:
df_compras.to_csv('shopping_behavior_updated_treated.csv', encoding='utf-8', index=False)